services:
  fondofakeneo_export_connector.provider.form.job_instance:
      class: '%pim_enrich.provider.form.job_instance.class%'
      arguments:
          -
            fondofakeneo_csv_product_export: pim-job-instance-csv-product-export
      tags:
          - { name: pim_enrich.provider.form }